hostname: https://line-reversibot.herokuapp.com
your_turn_format: "{}は{}です。"
first_attack: "先攻"
second_attack: "後攻"
finish_format: "{} - {}\nあなたの{}"
win_string: "勝ち"
lose_string: "負け"
ai_passing: "パス!"
your_passing: "あなたのパス!"
help: "「オセロ」でスタートします\n「guide on」でマス上に番号が表示されます\n「guide off」でマス上の番号が消えます\n「reload」でもう一度今の盤面を送信します\n「オセロ help」でこのメッセージを出します"
